#' Generate random samples from a primary event censored distribution
#'
#' This function generates random samples from a primary event censored
#' distribution. It adjusts the distribution by accounting for the primary
#' event distribution and potential truncation at a maximum delay (D). The
#' function allows for custom primary event distributions and delay
#' distributions.
#'
#' @inheritParams dprimarycensoreddist
#'
#' @param rdist Function to generate random samples from the delay distribution
#' for example [stats::rlnorm()] for lognormal distribution.
#'
#' @param n Number of random samples to generate.
#'
#' @param rprimary Function to generate random samples from the primary
#' distribution (default is [stats::runif()]).
#'
#' @param rprimary_args List of additional arguments to be passed to rprimary.
#'
#' @param oversampling_factor Factor by which to oversample the number of
#' samples to account for truncation (default is 1.2).
#'
#' @param ... Additional arguments to be passed to the distribution function.
#'
#' @return Vector of random samples from the primary event censored
#' distribution
#'
#' @aliases rpcens
#'
#' @importFrom stats runif
#'
#' @export
#'
#' @details
#' The primary event censored random samples are generated by first
#' oversampling to account for potential truncation. Primary event times are
#' generated from the specified primary event distribution, and delays are
#' generated from the specified delay distribution. The total delays are
#' calculated by adding the primary event times and the delays. These total
#' delays are then rounded to the nearest secondary event window (swindow).
#' Truncation is applied to ensure that the delays are within the specified
#' range \[0, D\]. If the number of valid samples is less than the desired
#' number of samples (n), additional samples are generated until the required
#' number of valid samples is obtained.
#'
#' @family primarycensoreddist
#'
#' @examples
#' # Example: Lognormal distribution with uniform primary events
#' rprimarycensoreddist(10, rlnorm, meanlog = 0, sdlog = 1)
#'
#' # Example: Lognormal distribution with exponential growth primary events
#' rprimarycensoreddist(
#'   10, rlnorm,
#'   rprimary = rexpgrowth, rprimary_args = list(r = 0.2),
#'   meanlog = 0, sdlog = 1
#' )
rprimarycensoreddist <- function(n, rdist, pwindow = 1, swindow = 1,
                                 D = Inf, rprimary = stats::runif,
                                 rprimary_args = list(),
                                 oversampling_factor = 1.2, ...) {
  # Generate more samples than needed to account for truncation
  n_generate <- ceiling(n * oversampling_factor)

  # Generate primary event times
  p <- do.call(
    rprimary, c(list(n_generate), rprimary_args, list(min = 0, max = pwindow))
  )

  # Generate delays from the specified distribution
  delay <- rdist(n_generate, ...)

  # Calculate total delays
  total_delay <- p + delay

  # Round to the nearest swindow
  rounded_delay <- floor(total_delay / swindow) * swindow

  # Apply truncation and select valid samples
  valid_samples <- rounded_delay[rounded_delay >= 0 & rounded_delay < D]

  # If we don't have enough samples, generate more
  while (length(valid_samples) < n) {
    additional_samples <- rprimarycensoreddist(
      n - length(valid_samples), rdist, pwindow, swindow, D, rprimary,
      rprimary_args, ...
    )
    valid_samples <- c(valid_samples, additional_samples)
  }

  # Return exactly n samples
  samples <- valid_samples[1:n]

  return(samples)
}

#' @rdname rprimarycensoreddist
#' @export
rpcens <- rprimarycensoreddist
