on:
  push:
    paths:
      - DESCRIPTION
      - .github/workflows/codemeta.yml
  workflow_dispatch:

name: Render codemeta

jobs:
  render:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'cm-skip')"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://stan-dev.r-universe.dev'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::codemetar
          needs: codemeta

      - name: Render codemeta
        run: codemetar::write_codemeta()
        shell: Rscript {0}

      - name: Create Pull Request
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update codemeta.json"
          title: "Update codemeta.json"
          body: "This is an automated pull request to update the codemeta.json file."
          branch: "update-codemeta-${{ github.run_number }}"
          labels: "metadata"
          reviewers: seabbs
          add-paths: |
            codemeta.json
          token: ${{ secrets.GITHUB_TOKEN }}
